<script>
  import { decodeMessageFromCanvas } from "../infrastructure/steganography/canvasSteganography.js";

  const sizeFormatter = new Intl.NumberFormat("en-US");

  let fileInput;
  let previewCanvas;
  let imageName = "";
  let imageSize = 0;
  let imageWidth = 0;
  let imageHeight = 0;
  let decodeError = "";
  let decodeStatus = "Upload a PNG from Steganova to extract its hidden sentence.";
  let decodedMessage = "";
  let hiddenMessageFound = false;

  function openFilePicker() {
    fileInput?.click();
  }

  async function handleFileChange(event) {
    const file = event.currentTarget.files?.[0];
    event.currentTarget.value = "";

    if (!file) {
      return;
    }

    await decodeFile(file);
  }

  async function decodeFile(file) {
    decodeError = "";
    decodeStatus = "Loading image…";
    decodedMessage = "";
    hiddenMessageFound = false;
    imageName = file.name;
    imageSize = file.size;

    try {
      const image = await loadImage(file);
      const context = previewCanvas?.getContext("2d", { willReadFrequently: true });
      if (!context || !previewCanvas) {
        throw new Error("Unable to prepare the preview canvas.");
      }

      imageWidth = image.naturalWidth;
      imageHeight = image.naturalHeight;
      previewCanvas.width = imageWidth;
      previewCanvas.height = imageHeight;
      context.clearRect(0, 0, imageWidth, imageHeight);
      context.drawImage(image, 0, 0, imageWidth, imageHeight);

      const message = decodeMessageFromCanvas(previewCanvas);
      if (message === null) {
        decodeStatus = "No hidden Steganova message was detected in this image.";
        return;
      }

      hiddenMessageFound = true;
      decodedMessage = message;
      decodeStatus =
        message.length > 0
          ? "Hidden message successfully decoded."
          : "An empty hidden message was detected in this image.";
    } catch (error) {
      imageWidth = 0;
      imageHeight = 0;
      decodeError =
        error instanceof Error && error.message.length > 0
          ? error.message
          : "Unable to decode the uploaded image.";
      decodeStatus = "Decoding failed.";
    }
  }

  async function copyDecodedMessage() {
    if (!hiddenMessageFound) {
      return;
    }

    try {
      await navigator.clipboard.writeText(decodedMessage);
      decodeStatus = "Decoded message copied to the clipboard.";
    } catch {
      decodeStatus = "Copy failed. The decoded message is still visible below.";
    }
  }

  function resetDecoder() {
    imageName = "";
    imageSize = 0;
    imageWidth = 0;
    imageHeight = 0;
    decodeError = "";
    decodeStatus = "Upload a PNG from Steganova to extract its hidden sentence.";
    decodedMessage = "";
    hiddenMessageFound = false;

    if (previewCanvas) {
      const context = previewCanvas.getContext("2d", { willReadFrequently: true });
      context?.clearRect(0, 0, previewCanvas.width, previewCanvas.height);
      previewCanvas.width = 0;
      previewCanvas.height = 0;
    }

    if (fileInput) {
      fileInput.value = "";
    }
  }

  function loadImage(file) {
    return new Promise((resolve, reject) => {
      const objectUrl = URL.createObjectURL(file);
      const image = new Image();

      image.onload = () => {
        URL.revokeObjectURL(objectUrl);
        resolve(image);
      };

      image.onerror = () => {
        URL.revokeObjectURL(objectUrl);
        reject(new Error("The selected file could not be read as an image."));
      };

      image.src = objectUrl;
    });
  }
</script>

<section class="workspace-grid">
  <article class="composer-panel plain-frame">
    <div class="section-head">
      <div>
        <p class="section-kicker">Decode</p>
        <h1>Upload an image</h1>
      </div>
    </div>

    <input bind:this={fileInput} class="visually-hidden" type="file" accept="image/png,image/*" on:change={handleFileChange} />

    <div class="decode-dropzone">
      <p class="section-note">Upload a PNG generated by Steganova. The image is drawn into a canvas at full size, then the hidden payload is read back.</p>

      <div class="button-row">
        <button class="action primary" type="button" on:click={openFilePicker}>Choose image</button>
        <button class="action ghost" type="button" on:click={resetDecoder}>Reset</button>
      </div>
    </div>

    <div class="status-block">
      <p class="section-note">{decodeStatus}</p>
      {#if imageName}
        <div class="decode-metrics">
          <span class="metric-pill">{imageName}</span>
          <span class="metric-pill dashed">{sizeFormatter.format(imageSize)} bytes</span>
          {#if imageWidth > 0 && imageHeight > 0}
            <span class="metric-pill dotted">{imageWidth} × {imageHeight}</span>
          {/if}
        </div>
      {/if}
    </div>

    {#if decodeError}
      <p class="decode-error">{decodeError}</p>
    {/if}

    <label class="decode-result">
      <span class="section-kicker">Decoded message</span>
      <textarea readonly class="decode-output" placeholder="The hidden sentence will appear here.">{decodedMessage}</textarea>
    </label>

    <div class="button-row">
      <button class="action secondary" type="button" on:click={copyDecodedMessage} disabled={!hiddenMessageFound}>
        Copy message
      </button>
    </div>
  </article>

  <section class="result-panel dashed-frame">
    <div class="section-head">
      <div>
        <p class="section-kicker">Preview</p>
        <h2>Uploaded image</h2>
      </div>
      <span class="side-note">{hiddenMessageFound ? "message found" : "waiting"}</span>
    </div>

    <div class="preview-shell">
      <canvas bind:this={previewCanvas} aria-label="Uploaded artwork preview"></canvas>

      {#if !imageName}
        <div class="preview-empty">
          <p>No image loaded yet.</p>
        </div>
      {/if}
    </div>

    <p class="footer-note">
      Steganova decoding works only if the PNG still preserves the original pixel data. Heavy recompression or screenshots may destroy the hidden bits.
    </p>
  </section>
</section>

<style>
  .visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }

  .decode-dropzone,
  .status-block {
    display: flex;
    flex-direction: column;
    gap: 12px;
    padding: 14px;
    border-radius: 18px;
    border: 2px dashed var(--ink);
    background: rgba(255, 255, 255, 0.68);
  }

  .decode-metrics {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }

  .metric-pill {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 8px 12px;
    border-radius: 999px;
    border: 1.5px solid var(--ink);
    background: var(--paper);
    color: var(--ink);
    font: 700 0.72rem/1 var(--font-mono);
    letter-spacing: 0.08em;
  }

  .metric-pill.dashed {
    border-style: dashed;
  }

  .metric-pill.dotted {
    border-style: dotted;
  }

  .decode-result {
    display: flex;
    flex-direction: column;
    gap: 8px;
    min-height: 0;
    flex: 1;
  }

  .decode-output {
    width: 100%;
    min-height: 0;
    flex: 1;
    padding: 16px;
    border: 2px solid var(--ink);
    border-radius: 18px;
    resize: none;
    background:
      repeating-linear-gradient(
        180deg,
        transparent 0,
        transparent 32px,
        rgba(17, 17, 17, 0.04) 32px,
        rgba(17, 17, 17, 0.04) 33px
      ),
      rgba(255, 255, 255, 0.92);
    color: var(--ink);
    font: 500 0.98rem/1.7 var(--font-body);
  }

  .decode-error {
    margin: 0;
    padding: 12px 14px;
    border: 2px dotted var(--ink);
    border-radius: 18px;
    background: rgba(17, 17, 17, 0.04);
    color: var(--ink);
  }

  .preview-shell {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    flex: 1;
    min-height: 0;
    overflow: hidden;
    border: 2px solid var(--ink);
    border-radius: 18px;
    background: var(--paper);
    padding: 14px;
  }

  .preview-shell canvas {
    display: block;
    max-width: 100%;
    max-height: 100%;
    width: auto;
    height: auto;
    background: var(--paper);
  }

  .preview-empty {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--ink-faint);
    font: 700 0.8rem/1 var(--font-mono);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    pointer-events: none;
  }
</style>
